name       : uhttpmock
version    : 0.5.0
release    : 1
source     :
    - http://tecnocode.co.uk/downloads/uhttpmock/uhttpmock-0.5.0.tar.xz : 26da182a2db2579c5ba4dad9096d52099e0766228c295cfbaed6de4046f7d16e
license    : LGPL-2.1
summary    : HTTP web service mocking project for projects which use libsoup
description: |
    HTTP web service mocking project for projects which use libsoup
builddeps  :
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
