name       : uhttpmock
version    : 0.5.1
release    : 3
source     :
    - http://tecnocode.co.uk/downloads/uhttpmock/uhttpmock-0.5.1.tar.xz : a6a34a011db142a98473b492039c84468d575f416689484f1f82a84927f17798
license    : LGPL-2.1-or-later
summary    : HTTP web service mocking project for projects which use libsoup
description: |
    HTTP web service mocking project for projects which use libsoup
component  : programming.tools
builddeps  :
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
