name       : uhttpmock
version    : 0.5.3
release    : 5
source     :
    - http://tecnocode.co.uk/downloads/uhttpmock/uhttpmock-0.5.3.tar.xz : 90843223c3a30bdb7f1eb3442373a03fee425af85a9df289cd687698ccff112f
license    : LGPL-2.1-or-later
component  : programming.tools
homepage   : https://gitlab.com/uhttpmock/uhttpmock
summary    : HTTP web service mocking project for projects which use libsoup
description: |
    HTTP web service mocking project for projects which use libsoup
builddeps  :
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
